### ISSUE TITLE
Crash with Buddypress 8.00 update

### ISSUE THREAD

**Issue by superbenj** [imath/profil-de-groupes#3]
Hi,
Great plugin but not working anymore with Buddypress 8 update..
By the way is there a plugin to make hierarchical group types? Like group categories and subcategories.
Thanks

Warning: Declaration of Profil_De_Groupes_Group_Data::get_data_for_user($user_id, $field_ids) should be compatible with BP_XProfile_ProfileData::get_data_for_user($user_id, $field_ids, $field_type_objects = Array) in /Users/xxxx/Local Sites/fxxxxxx/app/public/wp-content/plugins/profil-de-groupes-master/inc/classes/class-profil-de-groupes-group-data.php on line 19

**Comment by imath** [comment]
Thanks for your feedback, I'll look at it asap 👌

**Comment by imath** [comment]
Hi, I believe I've fixed your issue and (actually some others). I still need to run some additional tests before releasing a new version of the plugin. If you want to test the fixes, you can checkout this branch https://github.com/imath/profil-de-groupes/tree/fix/bp8-issues

**Comment by superbenj** [comment]
Bonjour,

Ça marche super. Bravo et merci.

Serait il possible que les nouveaux champs soient dans le premier onglet de la création de projet? Onglet « Détails ».
Sinon, je souhaiterai avoir un champ « Description courte « (Group description)  avec max 100 caratères dans l’onglet « Détails », visible dans les fiches des groupes du répertoire des groupe, (chez moi ce sont des projets) et un champ   "Description détaillée" plus long.
J’ai réussi (en bricolant le code) a changer le titre de « Group description en "Description courte » et à le limiter à 100 caractères et à créer grâce à votre plugin un champ "Description détaillée » 
Seulement les nouveaux champs crées ont un cadre limité qui ne convient pas à une description.
Auriez vous une solution?

En voir remerciant pour vos contributions.

Superbenj

Hello,

It works great. Well done and thank you.

Would it be possible to put the new fields in the first tab of the project creation? "Details" tab.
Otherwise, I would like to have a "Short Description" field (Group description) with max 100 characters in the "Details" tab, visible in the groups cards in Group directory and a longer "Detailed description" field .
I managed (by tinkering with the code) to change the title from "Group description to" Short description "and to limit it to 100 characters and to create with your plugin a " Detailed description " field.
Only the newly created fields have a limited frame which is not suitable for a description.
Do you have a solution?

See thanking for your contributions.

Superbenj
